version: '2.1'
orbs:
  gh: circleci/github-cli@2.2.0


jobs:
  build:
    docker:
      - image: cimg/go:1.21.1
    steps:
      - checkout
      - run:
          name: foo
          command: |
            go build

workflows:
  test-and-deploy:
    jobs:
      - build
      #- test
      - gh/release:
          context:
            - GITHUB_CREDS
          prerelease: true
          files: ./lilypad
          filters:
            branches:
              # TODO: switch to only releasing on tags
              only:
                - main
          requires:
            - build
          tag: 0.0.1-<<pipeline.git.revision>>
          title: Release <<pipeline.git.revision>>
