version: '2.1'
orbs:
  gh: circleci/github-cli@2.2.0


jobs:
  build:
    docker:
      - image: cimg/go:1.21.1
    steps:
      - checkout
      - run:
          name: Build
          command: |
            mkdir -p build/Linux-x86_64
            go build -o build/Linux-x86_64/lilypad
      - persist_to_workspace:
          root: build/
          paths:
           - Linux-x86_64

  release:
    docker:
      - image: cimg/go:1.21.1
    steps:
      - attach_workspace:
          at: /tmp/build
      - checkout
      - run:
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
          name: GitHub release
          command: |
            if [ ! -z "<<pipeline.git.tag>>" ]; then
              wget https://github.com/cli/cli/releases/download/v2.35.0/gh_2.35.0_linux_amd64.deb
              sudo dpkg -i gh_2.35.0_linux_amd64.deb
              gh release create <<pipeline.git.tag>> --notes "Release <<pipeline.git.tag>> for Linux x86_64" <<pipeline.git.tag>> /tmp/build/Linux-x86_64/lilypad
            else
              echo "Skipping missing tag"
            fi


workflows:
  test-and-deploy:
    jobs:
      - build
      #- test
      - release:
          requires:
            - build
